CORRECT_CONNECTOR: [
    "Wow, that actually makes a lot of sense now.",
    "Ah, now I get it. Seeing it this way really boosts my confidence.",
    "It all makes sense now, this gives me a solid foundation to move forward.",
    "Now that’s convincing, it really does.",
    "That's quite clear now.",
    "This seems logically sound.",
    "This matches the logical expectation.",
    "I can see the reasoning fits well here.",
    "Yes, that checks out.",
    "Everything fits together nicely.",
    "Right, that was the missing piece.",
    "Indeed, this supports the claim well.",
    "Up to this point, the logic remains solid.",
    "That was a clean deduction.",
    "Looks consistent with earlier steps.",
    "There’s no contradiction here.",
    "That's internally consistent.",
    "Solid logic so far.",
    "This explanation holds up.",
    "Now everything is falling into place."
]

INCORRECT_CONNECTOR: [
    "However, this might not be the right path because",
    "We should verify this step before moving on.",
    "Let’s break this down into simpler steps.",
    "Working backwards, we see that we need...",
    "Wait, that doesn't seem to follow.",
    "Hmm, that might be a dead end.",
    "That step could be flawed.",
    "There could be a mistake here.",
    "This seems inconsistent with earlier logic.",
    "This doesn’t lead where we want it to.",
    "That assumption might be too strong.",
    "Let’s re-evaluate that approach.",
    "Not quite the result we hoped for.",
    "Possibly an error in reasoning here.",
    "This result feels suspicious.",
    "I might have overlooked something.",
    "Let’s pause and rethink this.",
    "That logic seems a bit shaky.",
    "This contradicts a previous result.",
    "Needs further inspection before continuing."
]